version: '3'
networks:
  dkrtest_foo:
    driver: bridge
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: dkrsrv
    networks:
      - dkrtest_foo
  test:
    environment:
      - is_docker=yes
    build:
      context: tests/.
      dockerfile: Dockerfile.smoke-test
    container_name: dkrtest
    networks:
      - dkrtest_foo
