version: '3'
networks:
  dkrtest_foo:
    driver: bridge
services:
  web:
    build: .
    container_name: dkrsrv
    networks:
      - dkrtest_foo
  test:
    environment:
      - is_docker=yes
    build: tests/.
    container_name: dkrtest
    networks:
      - dkrtest_foo
